version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.node
    image: code-crisp-backendv3
    container_name: myapp-node-server
    command: node ./index.js
    volumes:
      - . :/app
      - /app/node_modules
    ports:
      - "8070:8070"
    depends_on:
      - mongo
    env_file: .env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./codecrisp-frontend
      dockerfile: Dockerfile.reactUI
    image: code-crisp-frontend
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./codecrisp-frontend:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local